# echo -n 'admin' | base64
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: production
type: Opaque
data:
  PORT: "ODAwMA==" # 8000
  MONGODB_URL: bW9uZ29kYitzcnY6Ly93YXRjaHdhdmVraW5kOnZqdnBuNDB0cFZKSWYwaHpAd2F0Y2h3YXZlLXN0cmVtaWZ5LmJ1ZG1qLm1vbmdvZGIubmV0Lw==
  CORS_ORIGIN_PRODUCTION: c3RyZWFtaWZ5LmFobWFkcmF6YS5pbg==
  CORS_ORIGIN_DEV: c3RyZWFtaWZ5LmFobWFkcmF6YS5pbg==
  ACCESS_TOKEN_SECRET: VUF1eXZCSmJoVkhJVFlLSEJLVnZrQml1ZkJuSFVWdHlma0dKVmJV
  ACCESS_TOKEN_EXPIRY: MWQ=
  REFRESH_TOKEN_SECRET: dXR2QktIVnl1dGNqdkJCR0N5ZmpnY3ZrakJLSkNUeWZnY1ZKSEJodkNIVm1qaGI=
  REFRESH_TOKEN_EXPIRY: MTBk
  CLOUDINARY_CLOUD_NAME: ZHA4Zmlzbmhz
  CLOUDINARY_API_KEY: ODUzMzcyNTI1NTMzNDU1
  CLOUDINARY_API_SECRET: R21Ec1otVWFwLVo1YlVwZHRNVmJ6WHZXVU5j


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: noscopev6/watchwave-backend:v0.0.7
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: app-secrets
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: production
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
