name: Build and Push Docker Images

on:
  push:
    tags:
      - "*"  # Trigger only on tag creation

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    env:
      REGISTRY: docker.io   # Docker Hub registry
      FRONTEND_IMAGE_NAME: noscopev6/watchwave-frontend  # Image name for the frontend
      BACKEND_IMAGE_NAME: noscopev6/watchwave-backend    # Image name for the backend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Push Frontend Image
        working-directory: app-codebase/frontend
        run: |
          docker build --no-cache -t ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}:${{ github.ref_name }} .
          docker push ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}:${{ github.ref_name }}

      - name: Build and Push Backend Image
        working-directory: app-codebase/backend
        run: |
          docker build --no-cache -t ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}:${{ github.ref_name }} .
          docker push ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}:${{ github.ref_name }}
